#' Internal function that generates correlation and covariance matrices.
#'
#' Takes input generated by the 'calculate_mean_matrix' function and runs inside of it.
#'
#' @param mean_matrix Matrix - cell mean value matrix
#' @param sd_matrix Matrix - cell sd value matrix
#' @param rho Numeric - correlation of within factors
#' @param label_list List length 2 - Names of factor levels
#' @param nlfA Integer - number of levels of factor A
#' @param nlfB Integer - number of levels of factor B
#'
#' @return list length 2 with covariance and correlation matrices
#'
#' @export
gencovmat <- function(mean_matrix, sd_matrix, rho=rho, label_list, withinf, nlfA, nlfB)
  {
  cnames <- expand.grid(label_list[[2]], label_list[[1]])
  cnames <- paste(cnames$Var2, cnames$Var1, sep = "_")

  cormat <- diag(1, prod(nlfA, nlfB))
  rownames(cormat) <- colnames(cormat) <- cnames

  sigmat <- diag(0, prod(nlfA, nlfB))
  rownames(sigmat) <- colnames(sigmat) <- cnames
  if(length(sd_matrix)==1)
  {
    sd_matrix <- matrix(sd_matrix, nrow = nrow(mean_matrix), ncol = ncol(mean_matrix))
  }

  if(withinf=="fA")
  {
    rowpos <- sapply(1:nlfB, function(x) grep(paste0("_", label_list[[2]][x], "$"), rownames(cormat)))
    colpos <- sapply(1:nlfB, function(x) grep(paste0("_", label_list[[2]][x], "$"), colnames(cormat)))
    if(all.equal(rowpos, colpos))
    {
      for(x in seq(nlfB))
      {
        cormat[rowpos[,x], colpos[,x]] <- rho
        diag(cormat) <- 1
        sigmat[rowpos[,x], colpos[,x]] <- cormat[rowpos[,x], colpos[,x]]*tcrossprod(sd_matrix[,x])
      }
    }
  }
  if(withinf=="fB")
  {
    rowpos <- sapply(1:nlfA, function(x) grep(paste0("^", label_list[[1]][x], "_"), rownames(cormat)))
    colpos <- sapply(1:nlfA, function(x) grep(paste0("^", label_list[[1]][x], "_"), colnames(cormat)))
    if(all.equal(rowpos, colpos))
    {
      for(x in seq(nlfA))
      {
        cormat[rowpos[,x], colpos[,x]] <- rho
      }
      diag(cormat) <- 1
      for(x in seq(nlfA))
      {
        x <- x-1
        sigmat[(x*nlfB)+(1:nlfB), (x*nlfB)+(1:nlfB)] <- cormat[(x*nlfB)+(1:nlfB), (x*nlfB)+(1:nlfB)]*tcrossprod(sd_matrix[x+1,])
      }
    }
  }
  if(withinf=="both")
  {
    cormat[cormat!=1] <- rho
    sigmat <- cormat*tcrossprod(as.vector(sd_matrix))
  }
  list(cormat=cormat, sigmat=sigmat)
}
