#' Internal function that plots modeled cell means and standard deviations and covariance matrices.
#' Takes input generated by the 'calculate_mean_matrix' function and runs inside of it.
#'
#' @param group_size integer - number of subjects in each group
#' @param matrices_obj List length 2 - Cell means and standard deviation matrices
#'
#' @return Line plot with expected mean and standard deviation for each combination of factor levels
#'
#' @export
graph_twoway_assumptions <- function(group_size=100, matrices_obj)
{
  require(ggpubr)
  if(length(matrices_obj)==2)
  {
    test_run <- twoway_simulation_independent(group_size=group_size, matrices_obj=matrices_obj, nsims=1)
  }else if (length(matrices_obj)==5)
  {
    test_run <- twoway_simulation_correlated(group_size=group_size, matrices_obj=matrices_obj, nsims=1)
  }
  fA <- names(test_run)[4]
  fB <- names(test_run)[5]
  p <- ggline(data=test_run, x = fB, y = "y", color = fA, add = c("mean_sd"),
            position = ggplot2::position_dodge(width = 0.15), size=1.1) + ggthemes::theme_few()
  p <- p + ggplot2::labs(y = "Mean\n± standard deviation", title=expression(paste("Mean cell ratio modeled ", mu[italic(ij)]," and ", sigma[italic(ij)]^2))) +
    ggplot2::theme(axis.text = ggplot2::element_text(size = 15), axis.title = ggplot2::element_text(size=15), legend.text = ggplot2::element_text(size = 15),
        plot.title = element_text(size = 20), legend.title = element_text(size = 15))
  p
}
