#' Graph modeled means and standard deviations of groups in two-way factorial design
#'
#' Internal function that plots modeled cell means and standard deviations and covariance matrices.
#' Takes input generated by the 'calculate_mean_matrix' function and runs inside of it.
#'
#' @param group_size integer - number of subjects in each group
#' @param matrices_obj List length 2 - Cell means and standard deviation matrices
#'
#' @return Line plot with expected mean and standard deviation for each combination of factor levels
#'
#' @export
graph_twoway_assumptions <- function(group_size=100, matrices_obj)
{
  if(length(matrices_obj)==2)
  {
    test_run <- twoway_simulation_independent(group_size=group_size, matrices_obj=matrices_obj, nsims=1)
  }else if (length(matrices_obj)==5)
  {
    test_run <- twoway_simulation_correlated(group_size=group_size, matrices_obj=matrices_obj, nsims=1)$simulated_data
  }
  fA <- names(test_run)[4]
  fB <- names(test_run)[5]
  test_run[,4] <- gsub(paste0("^", fA, "_"), "", test_run[,4])
  test_run[,5] <- gsub(paste0("^", fB, "_"), "", test_run[,5])
  summarized_test <- summarySEwithin(test_run, measurevar = "y", groupvars=c(fA, fB))
  p <- ggplot2::ggplot(data=summarized_test, aes(x = fB, y = "y", color = fA)) +
    geom_errorbar(aes(ymin=len-se, ymax=len+se), width=.1) +
    geom_line(position = ggplot2::position_dodge(width = 0.15), size=1.1) +
    geom_point(position = ggplot2::position_dodge(width = 0.15), size=1.1) + ggthemes::theme_few()
  p <- p + ggplot2::labs(y = "Outcome\n\u00B1 standard deviation", title=expression(paste("Mean cell ratio modeled ", mu[italic(ij)]," and ", sigma[italic(ij)]^2))) +
    ggplot2::theme(axis.text = ggplot2::element_text(size = 15), axis.title = ggplot2::element_text(size=15), legend.text = ggplot2::element_text(size = 15),
        plot.title = ggplot2::element_text(size = 20), legend.title = ggplot2::element_text(size = 15))
  p
}
