#' Simulated independent and repeated measures two-way experiments over a set of sample sizes
#'
#' Wrapper for both independent and repeated measures two-way simulations. A vector of defined sample sizes is simulated under the
#' model provided.
#'
#' @param matrices_obj List - Output generated by 'calculate_mean_matrix' that include cell mean and covariance matrices
#' @param nrange Vector - Sample sizes to be used in simulations.
#' @param repeated_measurements Logical - Does the design have repeated measurements. Default is false.
#' @param distribution Character - - Type of distribution to simulate. Only implemented for independent designs. Possible values are 'normal', 'truncated' or 'skewed'.
#' @param skewness Numeric - Momentum of distribution skewness
#' @param inferior_limit Numeric - Value of the lower bound for the truncated distribution, defaults to '-Inf'
#' @param superior_limit Numeric - Value of the upper bound for the truncated distribution, defaults to 'Inf'
#' @param nsims Integer - Number of iterations
#'
#' @return List with of data.frames of simulated outcome values under different sample sizes. Each data.frame includes factor level labels, iteration number and sample size.
#'
#' @examples
#' refmean <- 1
#' treatgroups <- 4
#' timepoints <- 5
#' treateff <- 1.5
#' timeeff <- 0.85
#' ## Independent design
#' effects_treat_time <- calculate_mean_matrix(refmean = refmean, fAeffect = treateff, fBeffect = timeeff, nlfA = treatgroups, nlfB = timepoints, label_list = list(treatment=letters[1:treatgroups], time=1:timepoints))
#' ## Inspect plot to check if matrices correspond to design
#' n <- seq(from = 16, to = 24, by = 2)
#'
#' ## In this case, the default 'repeated_measurements', 'distribution' and options are used.
#' indep_simulation <- simulate_twoway_nrange(effects_treat_time, n)
#'
#' @export
simulate_twoway_nrange <- function(matrices_obj, nrange, repeated_measurements=FALSE, distribution="normal", skewness=1, inferior_limit=-Inf, superior_limit=Inf, nsims=500)
  {
  if(!repeated_measurements & length(matrices_obj[[1]])==5)
    {
    stop("It seems you have given a correlation value and a within factor as input to the 'calculate_mean_matrix' function.\nAre you sure you want to leave 'repeated_measurements' as 'FALSE'?")
    }
  
  if(repeated_measurements & length(matrices_obj[[1]])==2)
    {
    stop("It seems you have not given a correlation value and a within factor as input to the 'calculate_mean_matrix' function.\nAre you sure you want to set 'repeated_measurements' to 'TRUE'?")
    }
  if(!repeated_measurements & length(matrices_obj[[1]])==2)
    {
    print("Simulating independent observations experiment")
    sim_overens <- lapply(nrange, twoway_simulation_independent, matrices_obj, distribution=distribution, skewness=skewness, inferior_limit=inferior_limit, superior_limit=superior_limit, nsims=nsims)
    } else if (repeated_measurements & length(matrices_obj[[1]])==5)
    {
    sim_overens <- lapply(nrange, twoway_simulation_correlated, matrices_obj, distribution=distribution, shape.parameter=skewness, inferior_limit=inferior_limit, superior_limit=superior_limit, nsims=nsims)
    }
  sim_overens
}
